spring:
  application:
    name: snpc
  datasource:
    url: jdbc:postgresql://localhost:5432/snpc_db
    username: snpc_user
    password: snpc_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework
  port: 9999

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#  api-docs:
#    path: /v3/api-docs